function mu_edge_cell = arithmetic_mean_mu_node(mu_node)

chkarg(istypesizeof(mu_node, 'complex', zeros(1, Axis.count)), ...
	'"mu_node" should be %dD array with complex elements.', Axis.count);

mu_edge_cell = cell(1, Axis.count);

mu_edge_cell{Axis.x} = (...
	mu_node(2:end, 2:end, 2:end) ...
	+ mu_node(2:end, 1:end-1, 2:end) ...
	+ mu_node(2:end, 2:end, 1:end-1) ...
	+ mu_node(2:end, 1:end-1, 1:end-1)...
) / 4;

mu_edge_cell{Axis.y} = (...
	mu_node(2:end, 2:end, 2:end) ...
	+ mu_node(2:end, 2:end, 1:end-1) ...
	+ mu_node(1:end-1, 2:end, 2:end) ...
	+ mu_node(1:end-1, 2:end, 1:end-1)...
) / 4;

mu_edge_cell{Axis.z} = (...
	mu_node(2:end, 2:end, 2:end) ...
	+ mu_node(1:end-1, 2:end, 2:end) ...
	+ mu_node(2:end, 1:end-1, 2:end) ...
	+ mu_node(1:end-1, 1:end-1, 2:end)...
) / 4;
