clear all; close all; clear classes; clc;

%% Set flags.
isnew = true;
inspect_only = true;

%% Solve the system.
if isnew
	%%
	gray = [0.5 0.5 0.5];  % [r g b]
	modeopts.clue = 'guess';
	modeopts.neff = 2;
	solveropts.method = 'inputfile';
	solveropts.filenamebase = mfilename;

	dL = 20;
	dl = 2;
	xn = -600 - 10	*dL;
	xp = -xn;
	yn = xn;
	yp = 300+10*dL;
	zn = -300 - 10*dL;
	zp = 300 + 10*dL;
	wo = 150;
	wi = 50;
	t = 25;
	T = 50;
	wvlen = 1550;
	[E, H, obj_array, src_array, J] = maxwell_run(...
		'OSC', 1e-9, wvlen, ...
		'DOM', {'vacuum', 'none', 1.0}, [xn xp; yn yp; zn zp], dL, BC.m, 10*dL, ...
		'OBJ', ...
			{'vacuum', 'none', 1.0}, ...
				Box([xn xp; yn yp; -wo/2-T wo/2+t], [dL dL dL/2]), ...
				Plane(Axis.z, 0), ...
				Plane(Axis.x, -400), ...
				Plane(Axis.x, 400), ...
				Plane(Axis.y, -400), ...
			{['CRC', filesep, 'Ag'], gray}, ...
				Box([xn xp; yn yp; zn -wo/2]), ...
				Box([xn xp; -wo/2-t wo/2+t; -wo/2 wo/2+t], [dL dl dl]), ...
			{['Palik', filesep, 'Si'], 'm'}, ...
				Box([xn xp; yn yp; zn -wo/2-T]), ...
			{['Palik', filesep, 'SiO2'], 'y'}, ...
				Box([xn xp; -wo/2 wo/2; -wo/2 wo/2], [dL dl dl]), ...
			{['CRC', filesep, 'Ag'], gray}, ...
				Box([xn xp; -wi/2 wi/2; -wi/2 wi/2], [dL dl dl]), ...
		'SRCJ', ModalSrc(Axis.x, -500, modeopts), ...
		solveropts, inspect_only);

	modalsrc = src_array;
	neff_guess = modalsrc.neff;

	if ~inspect_only
		save(solveropts.filenamebase, 'J', 'obj_array', 'src_array');
	end
else
	load(mfilename);
end
